---
title: "NYC Restaurant Inspections"
author: "Tao Wu"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Column {data-width=650}
-----------------------------------------------------------------------
```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)

data("rest_inspec")
data <- rest_inspec %>%
  mutate(cuisine = cuisine_description,
         grade = na_if(grade, ""),
         score = as.numeric(score), 
         inspection_date = as.Date(inspection_date)) %>%
  select(camis, dba, boro, cuisine, grade, score, inspection_date, latitude, longitude) %>%
  filter( !is.na(score),
          !is.na(latitude),
          !is.na(longitude),
)
data_pic <- data %>%
group_by(boro) %>%
slice_sample(n = 5000)%>%
mutate(
info = paste0("Name: ", dba, "Borough: ", boro, "Cuisine: ", cuisine, "Score: ", score)
)
plot <- plot_ly(data  = data_pic,x = ~longitude, y = ~latitude, type  = "scatter", mode  = "markers",
              color = ~score,text  = ~info, alpha = 0.1) %>%
  layout(
    title = "Restaurant Locations colored by Inspection Score",
    xaxis = list(title = "Latitude", range = c(-74.3, -73.7)),
    yaxis = list(title = "Longitude",range = c(40.5, 40.95))
  )
plot 
```
Column {data-width=350}
-----------------------------------------------------------------------
```{r, echo = FALSE, message=FALSE, warning=FALSE}
data_pic %>%
  filter(!is.na(score)) %>%
  mutate(boro = fct_reorder(boro, score)) %>%
  plot_ly(y = ~score,color = ~boro,type = "box") %>%
  layout(
    title = "Distribution of Inspection Scores by Borough",
    yaxis = list(title = "Score"),
    showlegend = TRUE
  )
data %>%
  filter(!is.na(score)) %>%
  count(boro) %>%
  mutate(boro = fct_reorder(boro, n)) %>%
  plot_ly(x = ~boro, y = ~n,type = "bar",color = ~boro) %>%
  layout(
    title = "Number of Restaurant Inspections by Borough",
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Number of Inspections"),
    showlegend = FALSE
  )
```

